name: Deploy demo

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: pip install sqlite-utils datasette
    - name: Build database
      run: |-
        echo '[
          {
            "package": "datasette-cluster-map",
            "url": "https://github.com/simonw/datasette-cluster-map"
          },
          {
            "package": "datasette-jellyfish",
            "url": "https://github.com/simonw/datasette-jellyfish"
          },
          {
            "package": "datasette-jq",
            "url": "https://github.com/simonw/datasette-jq"
          },
          {
            "package": "datasette-json-html",
            "url": "https://github.com/simonw/datasette-json-html"
          },
          {
            "package": "datasette-pretty-json",
            "url": "https://github.com/simonw/datasette-pretty-json"
          },
          {
            "package": "datasette-vega",
            "url": "https://github.com/simonw/datasette-vega"
          }
        ]' | sqlite-utils insert demo.db packages - --pk=package
    - name: Create Metadata
      run: |
        echo '{
            "title": "datasette-json-html demo",
            "about": "simonw/datasette-json-html",
            "about_url": "https://github.com/simonw/datasette-json-html"
        }' > metadata.json
    - name: Set up Cloud Run
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Deploy to Cloud Run
      run: |-
        gcloud config set run/region us-central1
        gcloud config set project datasette-222320
        datasette publish cloudrun demo.db \
          -m metadata.json \
          --install=https://github.com/simonw/datasette-json-html/archive/$GITHUB_SHA.zip \
          --service datasette-json-html-demo
